group_stage:
  enabled: true
  groups: # [name, teams per group]
    - ["A", 4]
    - ["B", 4]
    - ["C", 4]
    - ["D", 4]
  scheduling:
    parallel_games: false
    strategy: "round_robin"
    seeding: "sequential"
    advancement:
      spots_per_group: 2
      tiebreakers:
        - "points"
        - "goal_difference"
        - "goals_scored"
        - "head_to_head"

knockout_stage:
  quarterfinals:
    enabled: true
    format: "single_elimination"
    matchups: # [group_letter, position]      
      - [["A", 1], ["D", 2]]
      - [["B", 1], ["C", 2]]
      - [["C", 1], ["B", 2]]
      - [["D", 1], ["A", 2]]
  
  semifinals:
    enabled: true
    format: "single_elimination"
    matchups:
      - [["Quarterfinals", 1], ["Quarterfinals", 3]]
      - [["Quarterfinals", 2], ["Quarterfinals", 4]]
  
  finals:
    enabled: true
    bronze_medal_match: true
    last_position_match: true
    placement_matches:
      enabled: true
      positions: [13,11,9,7,5]

display:
  game_phase_names:
    group_stage: "Gruppenspiel"
    quarterfinals: "Viertelfinale"
    semifinals: "Halbfinale"
    placement: "Platzierungsspiel"
    bronze_medal: "Spiel um Platz 3"
    last_position_match: "Spiel um den letzten Platz"
    finals: "Finale"